apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: db
  name: metadata-postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: db
        sidecar.istio.io/inject: "false"
      name: db
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        envFrom:
        - configMapRef:
            name: metadata-registry-db-parameters
        - secretRef:
            name: metadata-registry-db-secrets
        image: postgres:14.7-alpine3.17
        name: db-container
        ports:
        - containerPort: 5432
          name: postgres
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 70
          runAsUser: 70
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: metadata-postgres
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: metadata-postgres
        persistentVolumeClaim:
          claimName: metadata-postgres
