apiVersion: v1
kind: Service
metadata:
  labels:
    component: db
  name: metadata-postgres-db
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
  selector:
    component: db
  type: ClusterIP
