apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: model-registry-server
  name: model-registry-configmap
data:
  MODEL_REGISTRY_DATA_STORE_TYPE: mlmd
  MODEL_REGISTRY_GRPC_SERVICE_HOST: model-registry-service
  MODEL_REGISTRY_GRPC_SERVICE_PORT: "9090"
  MODEL_REGISTRY_REST_SERVICE_HOST: model-registry-service
  MODEL_REGISTRY_REST_SERVICE_PORT: "8080"
