apiVersion: v1
kind: Service
metadata:
  annotations:
    description: An example model registry
    displayName: Kubeflow Model Registry
  labels:
    app: model-registry-service
    app.kubernetes.io/component: model-registry
    app.kubernetes.io/instance: model-registry-service
    app.kubernetes.io/name: model-registry-service
    app.kubernetes.io/part-of: model-registry
    component: model-registry
  name: model-registry-service
spec:
  ports:
  - appProtocol: http
    name: http-api
    port: 8080
    protocol: TCP
  - appProtocol: grpc
    name: grpc-api
    port: 9090
    protocol: TCP
  selector:
    component: model-registry-server
  type: ClusterIP
