apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: model-registry-server
  name: model-registry-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: model-registry-server
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "5432"
      labels:
        component: model-registry-server
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - args:
        - --grpc_port=$(MODEL_REGISTRY_GRPC_SERVICE_PORT)
        - --metadata_source_config_type=postgresql
        - --postgres_config_host=metadata-postgres-db
        - --postgres_config_port=5432
        - --postgres_config_dbname=$(POSTGRES_DBNAME)
        - --postgres_config_user=$(POSTGRES_USER)
        - --postgres_config_password=$(POSTGRES_PASSWORD)
        - --enable_database_upgrade=true
        command:
        - /bin/metadata_store_server
        env: []
        envFrom:
        - configMapRef:
            name: metadata-registry-db-parameters
        - secretRef:
            name: metadata-registry-db-secrets
        - configMapRef:
            name: model-registry-configmap
        image: gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
        livenessProbe:
          initialDelaySeconds: 3
          periodSeconds: 5
          tcpSocket:
            port: grpc-api
          timeoutSeconds: 2
        name: grpc-container
        ports:
        - containerPort: 9090
          name: grpc-api
        readinessProbe:
          initialDelaySeconds: 3
          periodSeconds: 5
          tcpSocket:
            port: grpc-api
          timeoutSeconds: 2
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 65534
          runAsUser: 65534
      - args:
        - --hostname=0.0.0.0
        - --port=8080
        - --mlmd-hostname=localhost
        - --mlmd-port=9090
        - --datastore-type=mlmd
        command:
        - /model-registry
        - proxy
        env: []
        image: ghcr.io/kubeflow/model-registry/server:latest
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          tcpSocket:
            port: http-api
          timeoutSeconds: 2
        name: rest-container
        ports:
        - containerPort: 8080
          name: http-api
        readinessProbe:
          initialDelaySeconds: 3
          periodSeconds: 5
          tcpSocket:
            port: http-api
          timeoutSeconds: 2
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: model-registry-server
